### ISSUE TITLE
Running the cloud-crowbar-testbuild-pr Jenkins job fails with encoding problems

### ISSUE THREAD

**Issue by gonzolino** [SUSE-Cloud/automation#2133]
The `scripts/jenkins/jenkins-job-trigger` script fails in our Jenkins job with a LookupError because of "unknown encoding: idna".

The following stack trace shows the error:
```
Triggering jenkins job with url http://<address>/mko/sap-oc:crowbar-openstack:37:db8e9b8ac89b7c5b0ab98bd402f115871f2783c9:stable/sap/3.0/ and directory /srv/mkcloud/mko/sap-oc:crowbar-openstack:37:db8e9b8ac89b7c5b0ab98bd402f115871f2783c9:stable/sap/3.0
Traceback (most recent call last):
  File "/root/github.com/SUSE-Cloud/automation/scripts/jenkins/jenkins-job-trigger", line 71, in <module>
    jenkins_build_job(sys.argv[1], args)
  File "/root/github.com/SUSE-Cloud/automation/scripts/jenkins/jenkins-job-trigger", line 63, in jenkins_build_job
    server.build_job(job_name, job_parameters)
  File "/usr/lib/python2.7/site-packages/jenkins/__init__.py", line 915, in build_job
    self.build_job_url(name, parameters, token), b''))
  File "/usr/lib/python2.7/site-packages/jenkins/__init__.py", line 344, in jenkins_open
    self.maybe_add_crumb(req)
  File "/usr/lib/python2.7/site-packages/jenkins/__init__.py", line 258, in maybe_add_crumb
    self._build_url(CRUMB_URL)), add_crumb=False)
  File "/usr/lib/python2.7/site-packages/jenkins/__init__.py", line 345, in jenkins_open
    response = urlopen(req, timeout=self.timeout).read()
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1194, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1041, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1075, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1037, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 881, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 843, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 824, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 554, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
LookupError: unknown encoding: idna

/root/github.com/SUSE-Cloud/automation/scripts/crowbar-testbuild.rb:124:in `trigger_jenkins_job'
/root/github.com/SUSE-Cloud/automation/scripts/crowbar-testbuild.rb:137:in `block in trigger_jenkins_jobs'
/root/github.com/SUSE-Cloud/automation/scripts/crowbar-testbuild.rb:136:in `each'
/root/github.com/SUSE-Cloud/automation/scripts/crowbar-testbuild.rb:136:in `trigger_jenkins_jobs'
/root/github.com/SUSE-Cloud/automation/scripts/crowbar-testbuild.rb:289:in `<main>'
```

We try to build & test the following PR https://github.com/sap-oc/crowbar-openstack/pull/37

**Comment by matelakat** [comment]
```
diff --git a/scripts/jenkins/jenkins-job-trigger b/scripts/jenkins/jenkins-job-trigger
index 3b7c7fe..7497ec3 100755
--- a/scripts/jenkins/jenkins-job-trigger
+++ b/scripts/jenkins/jenkins-job-trigger
@@ -57,7 +57,7 @@ def jenkins_build_job(job_name, job_args=[]):
         p_key, _, p_val = param.partition('=')
         job_parameters[p_key.strip(' ')] = p_val.strip(' ')

-    server = jenkins.Jenkins(config['jenkins_url'],
+    server = jenkins.Jenkins(str(config['jenkins_url']),
                              username=config['jenkins_user'],
                              password=config['jenkins_api_token'])
     server.build_job(job_name, job_parameters)
```

**Comment by matelakat** [comment]
That should be the fix.

Here is how to repro the error - it seems unicode hostnames are not liked there:
```
python -c 'import socket; socket.create_connection((u"<some-ip-here>", 8080));'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python2.7/socket.py", line 554, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
LookupError: unknown encoding: idna
```

whereas 
```
python -c 'import socket; socket.create_connection(("<some-ip-here>", 8080));'
```
is happyness

**Comment by matelakat** [comment]
https://github.com/SUSE-Cloud/automation/pull/2121

**Comment by jdsn** [comment]
fixed by https://github.com/SUSE-Cloud/automation/pull/2137
