### ISSUE TITLE
mkcloud cleanup in system without cloud-admin network

### ISSUE THREAD

**Issue by mimi1vx** [SUSE-Cloud/automation#345]
Traceback (most recent call last):
      File "./scripts/lib/libvirt/cleanup.py", line 79, in <module>
        main()
      File "./scripts/lib/libvirt/cleanup.py", line 68, in main
        network.undefine()
    UnboundLocalError: local variable 'network' referenced before assignment

**Comment by MaximilianMeister** [comment]
same issue as in https://github.com/SUSE-Cloud/automation/pull/347
as mentioned ther this should be fixed by https://github.com/SUSE-Cloud/automation/pull/343
